export interface PolymarketMarket {
  id: string; // This will now store the conditionId (0x...) for Data API compatibility
  gammaId: string; // The numeric/string ID from Gamma for URL linking
  question: string;
  slug: string;
  endDate: string;
  volume: number;
  liquidity: number;
  outcomes: string[];
  outcomePrices: string[];
}

export interface Trade {
  id: string;
  marketId: string; // conditionId
  marketQuestion: string;
  outcomeIndex: number;
  outcomeLabel: string;
  side: 'BUY' | 'SELL';
  price: number;
  size: number;
  timestamp: number;
  makerAddress: string;
  transactionHash: string;
}

export enum SuspicionLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export interface SuspiciousActivity {
  id: string;
  trade: Trade;
  suspicionScore: number; // 0-100
  level: SuspicionLevel;
  reasoning: string; // Generated by Gemini
  factors: string[]; // e.g., ["Fresh Wallet", "Whale Size", "Low Liquidity"]
  walletStats?: {
    totalTrades: number;
    winRate: number;
    accountAgeDays: number;
  };
}

export interface GeminiAnalysisResponse {
  suspicionScore: number;
  reasoning: string;
  factors: string[];
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}